seedChara = [
    {
      image: 'https://i.imgur.com/qOgSFcC.jpg',
      name: 'Eden Morgenstern',
      birthday: 'September 24',
      zodiac: 'Libra',
      birthplace: 'Natzal',
      bio: `Eden was raised in the system, and has a strong sense of justice, even if it's her own brand. As an adult she is a critically acclaimed artist, but she and her foster sister have a second secret job as a hacker named Nemesis (the goddess of divine retribution), and they deliver justice to those they deem guilty. She lives a good semi-normal life until she goes look for her own place and meets a man named Luca.`,
      idiosyncrasy: 'She and Eve (her foster sister) share a toothbrush. They did not consider this odd until told.',
      personality: 'Sarcastic, irreverent, rough-around the edges, loyal, and caring',
      relationships: 'She has had a few relationships, but none of them tend to be that serious. She not the type to want to be attached.',
      goalsMotivations: 'To be be freed from her destined/ordained path.',
      skills: 'Luck, celestial being handling, smiting, and suggestion',
      fearsWeakness: `Being alone.`,
      mostTreasured: `A (stolen) necklace Eve gave her when they were younger`,
      askForPermissionToUse: true,
      originalCreator: '_celestialelle_',
      instaLink: `https://www.instagram.com/_celestialelle_`,
      twitterLink: `https://twitter.com/_celestialelle_`,
      tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
    },
    {
        image: 'https://i.imgur.com/bytVvZh.png',
        name: 'Wren Devlin',
        birthday: 'April 31',
        zodiac: 'Taurus',
        birthplace: 'Maipala',
        bio: `Wren is a shy cinnamon roll with an extremely bad case of RBF, so many people think he is a threatening guy. In reality, he is a clumsy, shy, baker with a heart of gold.`,
        idiosyncrasy: 'Due to many people bullying him as a kid, he wears a beanie to hide his hair(color). He figures it one less thing to be noticed and pointed out.',
        personality: 'Kind hearted, fair, quiet, antisocial, strong-willed, dutiful, loyal, and brave.',
        relationships: 'None, but he has had a one going crush since childhood.',
        goalsMotivations: 'Support his family and prove that he does not need his father to do well in life.',
        skills: 'Baking, gardening, and fighting',
        fearsWeakness: 'Rejection',
        mostTreasured: 'His mother left a book of recipes behind from Maipala.',
        askForPermissionToUse: true,
        originalCreator: '_celestialelle_',
        instaLink: `https://www.instagram.com/_celestialelle_`,
        twitterLink: `https://twitter.com/_celestialelle_`,
        tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
      },
    {
      image: `https://i.imgur.com/BVVhTnq.jpg`,
      name: 'Anisa Lipatti',
      birthday: 'June 5',
      zodiac: 'Gemini',
      birthplace: 'Asrāwānwāla',
      bio: `Anisa was raised by her father's side of her family after her parents were killed. Her only motivation from then on was to hunt down whatever killed them.`,
      idiosyncrasy: `People are drawn to her despite making it clear she does not like people`,
      personality: 'Resourceful, brave, passionate, stubborn, a true friend, does not take no for an answer, convincing other people, athletic, and kind (in her own way)',
      relationships: 'She had many dalliance, a few serious relationships, but non worked because her partners felt they never truly knew her.',
      goalsMotivations: 'Revenge.',
      skills: 'Charm, Stealth, Strength, Agility, Healing, Suggestion on vampires',
      fearsWeakness: `Her weakness is her own distrust of others.`,
      mostTreasured: `A sari her mom saved for her for when she got older.`,
      askForPermissionToUse: true,
      originalCreator: '_celestialelle_',
      instaLink: `https://www.instagram.com/_celestialelle_`,
      twitterLink: `https://twitter.com/_celestialelle_`,
      tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
    },
    {
        image: 'https://i.imgur.com/Jwf3vSM.jpg',
        name: 'Freyja Chevalier',
        birthday: 'February 14',
        zodiac: 'Aquarius',
        birthplace: 'Corpus Christi, TX',
        bio: 'Freyja is an otome loving nerd that is very much not dating in the 3D world. That is until the goddess of love herself makes her a pawn of a game she desperately does not want to participate.',
        idiosyncrasy: `Loves to in water, cannot swim.`,
        personality: ` Charismatic, Persuasive, Clever, Witty, Analytical, Creative, Open-minded, Straightforward, Determined, and Resourceful`,
        relationships: `She has dated here and there, but when she felt like it got too serious she dipped.`,
        goalsMotivations: 'Finding her bliss.',
        skills: 'Coding, kickboxing, and gaming',
        fearsWeakness: 'Vulnerability',
        mostTreasured: `Nothing, not the type to value things so highly.`,
        askForPermissionToUse: true,
        originalCreator: '_celestialelle_',
        instaLink: `https://www.instagram.com/_celestialelle_`,
        twitterLink: `https://twitter.com/_celestialelle_`,
        tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
      },
      {
      image: 'https://i.imgur.com/0gxmqMR.jpg',
      name: 'Eira (Princess Eira of the Cháillay Forest. First Daughter of Queen Elphame and King Christsonday. Sole heir of the Throne of the Fey)',
      birthday: 'October 31',
      zodiac: 'Scorpio',
      birthplace: 'Cháillay Forest',
      bio: 'Eira was locked away for most of her life and was told it was to protect her, but she is one day awoken and it told that she might be the only one to stop an oncoming corruption.',
      idiosyncrasy: 'If her mom fixes her hair, when Eira goes back outside a gush of wind will put her hair back the way it was.',
      personality: 'Cheerful, Free spirited, Intelligent, and lacking in social graces if not in princess mode',
      relationships: 'She had a girlfriend when she was young and before she was locked away.',
      goalsMotivations: 'Be free and travel the world.',
      skills: 'Magic and attunement to nature.',
      fearsWeakness: `Being abandoned.`,
      mostTreasured: 'It used to be her stuffed bunny when she was a kid.',
      askForPermissionToUse: true,
      originalCreator: '_celestialelle_',
      instaLink: `https://www.instagram.com/_celestialelle_`,
      twitterLink: `https://twitter.com/_celestialelle_`,
      tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
    },
    {
      image: 'https://i.imgur.com/kIIjaGo.jpg',
      name: 'Ciel Aether',
      birthday: 'N/A',
      zodiac: 'N/A',
      birthplace: 'Mahparine',
      bio: `Ciel is from Mahparine. They are a colony that lives on the moon of Tharwa. Their race is held in high regard. She has stayed on Mahparine for most of her life, she has visited other worlds, but never for too long. When she leaves for her 'Iintibae it is her first time really being on her own in the world.`,
      idiosyncrasy: `When she gets too excited she'll begin to float.`,
      personality: 'Passionate, easily bored, rash, competitive, and loves to argue',
      relationships: `She has had a few relationships. She tends to take them seriously.`,
      goalsMotivations: `She wants to explore with her patron Vega and see what the world has to offer`,
      skills: 'Agile, fast, good at fighting, and avatar abilities',
      fearsWeakness: `Her biggest fear is being unremarkable, to spend a life that makes no difference at all. `,
      mostTreasured: `Her halo`,
      askForPermissionToUse: true,
      originalCreator: '_celestialelle_',
      instaLink: `https://www.instagram.com/_celestialelle_`,
      twitterLink: `https://twitter.com/_celestialelle_`,
      tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
    },
    {
        image: 'https://i.imgur.com/aEiAaM6.jpg',
        name: 'Denali Oren',
        birthday: 'N/A',
        zodiac: 'N/A',
        birthplace: `T'aaze'`,
        bio: `Denali was born on the planet of T'aaze'. He lived there for a while when he was a kid, but as he got older he became somewhat of a nomad. He is very worldly, but he never truly ingratiates himself. He is closest to his patron Sylvan.`,
        idiosyncrasy: 'Dislikes sleeping alone, but dislikes sleeping with people',
        personality: 'Clever, Sensitive, Reserved, Charismatic, Devote, and knowledgeable',
        relationships: `Had a few back in T'aaze' before he left. He is technically engaged, not that either party is fond of each other.`,
        goalsMotivations: `Survive.`,
        skills: 'Silver tongued, connected, and avatar abilities',
        fearsWeakness: `His biggest fear is being vulnerable and in turn being hurt. `,
        mostTreasured: 'He was betrayed by his family and on the run, so nothing.',
        askForPermissionToUse: true,
        originalCreator: '_celestialelle_',
        instaLink: `https://www.instagram.com/_celestialelle_`,
        twitterLink: `https://twitter.com/_celestialelle_`,
        tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
      },
      {
        image: 'https://i.imgur.com/mzPnIdR.jpg',
        name: 'Fae Hyung',
        birthday: 'March 23',
        zodiac: 'Aries',
        birthplace: 'Nunsong-i',
        bio: `She comes off very well behaved and elegant, but in reality she is feral.`,
        idiosyncrasy: `Despite seeming like a soft yet cold princess, her personality gives more of a mob boss at time.`,
        personality: 'Cunning, Determined, Mercurial, Fox-like, Snarky, Cocky, Intelligent, and Cold. Though she is this way, she acts very well-behaved to emulate her mother, though in reality her mother was also a bit of a wild child.',
        relationships: 'None, but she has had a one going crush since childhood.',
        goalsMotivations: 'Figuring out what she wants in life.',
        skills: 'Language, Infiltration, Tracking, Fighting, Firearms, Weapons, Toxicology, Connections, Being Rich',
        fearsWeakness: 'Disappointing those dear to her',
        mostTreasured: 'A musicbox that plays the lullaby her mother used to sing.',
        askForPermissionToUse: true,
        originalCreator: '_celestialelle_',
        instaLink: `https://www.instagram.com/_celestialelle_`,
        twitterLink: `https://twitter.com/_celestialelle_`,
        tiTokLink: `https://www.tiktok.com/@_celestialelle_`,
      }
]

const chara = mongoose.model('Chara', charaSchema);

module.exports = chara
